

/* Public */

module.exports = Signature;
function Signature() {
	this.includeComponentTypes = []; // List of component type classnames
	this.excludeComponentTypes = []; // List of component type classnames
	this.includesBitMask = 0; // Bitmap generated by the entity system
	this.excludesBitMask = 0; // Bitmap generated by the entity system
}

// Input array
Signature.prototype.setIncludedTypes = function(types) {
	this.includeComponentTypes = types;
}

// Input array
Signature.prototype.setExcludedTypes = function(types) {
	this.excludeComponentTypes = types;
}